# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'idobry/chartmuseumui:$(build.buildId)'

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerFile: Dockerfile

    imageName: 'idobry/charmuseumui:$(Build.BuildId)'

    includeLatestTag: true

