version: '2.0'
services:
  ui:
    build: ./
    #image: idobry/chartmuseumui:latest
    environment:
      CHART_MUSESUM_URL: http://chartmuseum:8080
    ports:
      - 3000:8080
  chartmuseum:
    image: chartmuseum/chartmuseum:v0.7.1
    ports:
    - 8080:8080
    volumes:
    - ./charts:/charts
    environment:
      PORT: 8080
      DEBUG: 1
    open:
    STORAGE: amazon
    STORAGE_AMAZON_BUCKET: my-s3-bucket
    STORAGE_AMAZON_PREFIX:
    STORAGE_AMAZON_REGION: us-east-1
  secret:
    AWS_ACCESS_KEY_ID: "AKIAIBNHEISAXGK2TEQA"
    AWS_SECRET_ACCESS_KEY: "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"
    
    

      
