version: '3.4'

services:
   ui:
     image: idobry/chartmuseumui:0.0.4
     environment:
      CHART_MUSESUM_URL: "http://chartmuseum:8080"
      AUTHENTICATION: "true"
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: user
      DB_NAME: db
     ports:
      - 9090:8080

   chartmuseum:
     image: chartmuseum/chartmuseum:latest
     volumes:
       - ~/.aws:/root/.aws:ro
     restart: always
     environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: "amazon"
      STORAGE_AMAZON_BUCKET: "imisight-chartmuseum"
      STORAGE_AMAZON_PREFIX: ""
      STORAGE_AMAZON_REGION: "eu-west-1"
     ports:
      - 8080:8080

   postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
      POSTGRES_DB: db