version: '2.0'
services:
  ui:
  build: ./
      image: idobry/chartmuseumui:latest
    environment:
      CHART_MUSESUM_URL: http://chartmuseum:8080
    ports:
      - 3000:8080
  chartmuseum:
    image: chartmuseum/chartmuseum:v7.1.0
    ports:
    - 8080:8080
    volumes:
    - ~/.aws:/root/.aws:ro
    environment:
      PORT: 8080
      DEBUG: 1
    open:
    STORAGE: "amazon"
    STORAGE_AMAZON_BUCKET: "chart01"
    STORAGE_AMAZON_PREFIX: "ranchername"
    STORAGE_AMAZON_REGION: "us-east-1"
  
    
    

      
